# Generated by Django 3.0.8 on 2020-07-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='f',
            field=models.IntegerField(default=0),
        ),
    ]
